### ISSUE TITLE
PROJ transform issue

### ISSUE THREAD

**Issue by NasH5169** [iulian0512/android_spatialite#3]
Dear iulian,

First thanks for the project, it was quite hard to find a recent build.

I managed to compile the AAR, I just add the System.loadLibrary to the SQLiteDatabase java class.

My existing spatial database is opening and the spatial queries like intersects are working well.

I just have an issue with the PROJ. A very simple query is not working:

`SELECT AsText(ST_Transform(MakePoint(0, 0, 4326), 3857))`

`org.spatialite.database.SQLiteException: ST_Transform exception - PROJ reports "proj_create: no database context specified". (code 1)`

I checked than the following queries gives the right results to be sure that the spatial ref sys has the projections infos.

`SELECT * FROM spatial_ref_sys WHERE srid IN (4326, 3857);`

Any idea?

Thanks!

**Comment by iulian0512** [comment]
hi, you do not need to compile it, its already compiled just include it like this in your android project 
```
dependencies {
    implementation 'com.github.iulian0512:android_spatialite:2.0.9'

}
```
now for the proj problem, this is most likely because proj needs an aditional definitions database to work 
run select PROJ_GetDatabasePath(); to check if a db path is set and select PROJ_SetDatabasePath("/my/path/to/db.db");
this is the projdb that is use currently
[projdb.zip](https://github.com/user-attachments/files/17678884/projdb.zip)

**Comment by NasH5169** [comment]
Hi,

You totally right. I saw that the proj.db is necessary. About that, the proj database the last .db generated with the OSGeo/PROJ repository is 9 MB, big size for just the few EPSG I need and it will make the APK of my app bigger than needed but this is another issue. :)

Thanks again.
